### ISSUE TITLE
Explore adding tracepath UDP ports to default firewall rules

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#101]
It was recently noted on the user list that we do not open the tracepath UDP ports 44444-44644 by default. It's unclear whether this is actually required (it's definitely not required for tracepath to report a result) but blocking it may limit things such as MTU changes on the destination host.

**Comment by igarny** [comment]
Hi Andy,

"but blocking it may limit things such as MTU changes on the destination host."
It seems to me this is the objective of the task:

to check if "blocking it may limit things such as MTU changes on the destination host"
 or do you have something else in mind?

question 2:

I can certainly see how you came up with this range "UDP ports 44444-44644", but the question is how did the user come up with it? How do we know it is the general case?


Best regards,
Ivan

**Comment by mfeit-internet2** [comment]
@igarny the base port 44444 is hard-wired into tracepath.

**Comment by arlake228** [comment]
On February 16, 2016 at 11:25:13 AM, Ivan Garnizov (notifications@github.com) wrote:

Hi Andy,

"but blocking it may limit things such as MTU changes on the destination host."
It seems to me this is the objective of the task:

to check if "blocking it may limit things such as MTU changes on the destination host"
or do you have something else in mind?

Correct, this is the objective of the issue I created. I am not sure whether they need to be open for tracepath to work at it’s full capability or not. 




question 2:

I can certainly see how you came up with this range "UDP ports 44444-44644", but the question is how did the user come up with it? How do we know it is the general case?

I will verify this the correct range when I tackle the issue. 




Best regards,
Ivan

**Comment by igarny** [comment]
Hi Andy,
I believe you have summarized it here:

From: Andrew Lake [mailto:andy@es.net] 
Sent: Dienstag, 16. Februar 2016 17:11
To: Garnizov, Ivan (RRZE)
Subject: RE: [perfsonar-user] Perfsonar ports - tracepath blocked

Hi Ivan,

It’s quite easy to recreate, all toolkits running our default firewall configuration display the same behavior. Keep in mind that he is not saying tracepath is completely failing, he just noted that the host firewall is rejecting tracepath packets which is generating ICMP prohibited message which are showing up in logs. Tracepath still “completes” in some sense, though it may not be detecting things like an MTU change on the end host.  I think his suspicion is correct that those ports being blocked by our iptables rules is just an oversight. Assuming it is, we simply need to add ports 44444-44644, similar to what we do for traceroute, and his logs won’t be flooded with complaints about tracepath getting rejected by the host firewall. We will also likely get a “better” tracepath result because it will be able to do MTU detection and similar on the end host.

Thanks,
Andy

**Comment by igarny** [comment]
Nevertheless I still believe we are rejecting correctly with:

-A INPUT -j REJECT --reject-with icmp-port-unreachable
-A FORWARD -j REJECT --reject-with icmp-port-unreachable


I am not sure, why you are referring to it with: 
"the host firewall is rejecting tracepath packets which is generating ICMP prohibited message"

Probably another REJECT type should be used?

**Comment by igarny** [comment]
The user has confirmed to me, that the prohibited reject message, comes from his FW on the router.
Nevertheless he claims our FW config of pS (did not give version) is missing the FW.

I suggest this issue to be closed as nothing to be done.

**Comment by arlake228** [comment]
Confirmed there is nothing to be done, closing.
