### ISSUE TITLE
Malformed .bashrc

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#145]
Ivan reported getting an error on boot because this was in his .bashrc file:

```
if [ -t 0 -a -t 1 -a -t 2 ]; then

fi

if [ -t 0 -a -t 1 -a -t 2 ]; then

# Run the add_psadmin_user script to ensure that a psadmin user has been created

/usr/lib/perfsonar/scripts/add_psadmin_user --auto

# Run the add_pssudo_user script to encourage disabling root ssh

/usr/lib/perfsonar/scripts/add_pssudo_user --auto

fi
```

**Comment by szymontrocha** [comment]
I confirm this error (in the latest update it's still there):

[psudouser@localhost ~]$ sudo bash
[sudo] password for psudouser:
ABRT has detected 2 problem(s). For more info run: abrt-cli list --since 1477051341
bash: /root/.bashrc: line 14: syntax error near unexpected token `fi'
bash: /root/.bashrc: line 14: `fi'
[root@localhost psudouser]#
[root@localhost psudouser]# cat /root/.bashrc
# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi
if [ -t 0 -a -t 1 -a -t 2 ]; then
fi
if [ -t 0 -a -t 1 -a -t 2 ]; then
# Run the add_psadmin_user script to ensure that a psadmin user has been created
/usr/lib/perfsonar/scripts/add_psadmin_user --auto
# Run the add_pssudo_user script to encourage disabling root ssh
/usr/lib/perfsonar/scripts/add_pssudo_user --auto
fi
[root@localhost psudouser]#
