### ISSUE TITLE
Toolkit regular testing GUI ignores aliased interfaces

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#149]
User reported that interfaces like eth0:0 or similar are ignored. We should probably not be ignoring these.

**Comment by lisaens** [comment]
Made changes to get_ethernet_interfaces() gets ALL interfaces, including loopbacks, state UP and UNKNOWN.  get_ips() gets all scope = global and scope = host addresses, loopbacks included. 
This is all in the branch intf_aliases_shared.

Fixed the Handlebars helper for the test-config interface selector (hostname_or_ip) to include ip addresses when hostnames are not available and remove duplicate hostnames and ips. 
This is in branch intf_aliases_toolkit.

**Comment by lisaens** [comment]
We need to get this tested in a variety of situations. Also check things other than the interface selector, eg, check the interfaces popup on the home page.

**Comment by lisaens** [comment]
Moved loopbacks to the end of the list in the interface selector and added a note after them (those that are named lo or lo:xx) - [note: loopbacks are not normally used in tests].

**Comment by apertome** [comment]
Merged these changes, good to go for RC2. We will likely make some changes based on feedback during the RC2 phase, so I'm leaving this open.

**Comment by apertome** [comment]
We had some fallout from this in that the discover_primary_interface function started detecting every host as "localhost" since it saw "lo" as the primary interface. This has been fixed in 069e7c13c96be63c02f58ca340622a7822006f59 but we may want to revisit this before the 4.0 final release. In particular, there's a chance there could be issues if hosts only have private interfaces. Needs more testing in that area.
