### ISSUE TITLE
Don't clobber pg_hba.conf

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/toolkit#254]
The toolkit supplies its own configuration for PostgreSQL (`etc/default_service_configs/pg_hba.conf`) that has an old pScheduler section in it.  pScheduler maintains its own section, so there's no need to do this.

I would recommend not replacing the entire file and perhaps using drop-in or something like it to add whatever is necessary.

**Comment by arlake228** [comment]
This file is only used by the perfsonar-toolkit-compat-database which handles migrating 3.5 archived data to postgresql-9.5. I think we can drop the file entirely and may just be an artifact of early iterations of the upgrade process. I don't think its actually doing anything meaningful since both esmond and pscheduler create those blocks on their own.

**Comment by mfeit-internet2** [comment]
andy [3:55 PM] 
i think we should keep it as I should probably just remove that file and line. right now its not doing anything but somewhere down the road it will probably break something
[3:55] 
at the very least its existence is confusing

**Comment by arlake228** [comment]
Actually. looking at this again we need it for 3.5 upgraders otherwise pscheduler won't install because we made md5 auth global in 3.5. Can drop this in 4.1, so moving there and marking as release-prep.

**Comment by arlake228** [comment]
Iceboxing this as we probably want to keep around the update process from pre-postgresql 9.5 awhile longer since we don't force central-management. It's also not really hurting anything.

**Comment by arlake228** [comment]
Closing. Actually this is not needed, removed in latest round of commits.
