### ISSUE TITLE
Add option to disable LS queries by GUI

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#274]
We keep getting questions about being able to disable the GUI from querying the lookup-service to see if the local host is registered. We should add a configuration option to do so. Note that this is just the queries performed by the GUI and nothing to do with registration.

**Comment by apertome** [comment]
This should be a setting in `web_admin.conf`.

Disabling ls lookups should be accomplished like this:
```disable_ls_lookups      1```

The default should be to check the LS to see if the host is registered -- this should happen if there is no value specified for `disable_ls_lookups` or if it is set to `0`

**Comment by apertome** [comment]
I think all you need to change is 
https://github.com/perfsonar/perl-shared/blob/83de1e5224fb3dd8cf2bf01786df31cc76b43d17/lib/perfSONAR_PS/NPToolkit/DataService/Host.pm#L269

and 

https://github.com/perfsonar/perl-shared/blob/83de1e5224fb3dd8cf2bf01786df31cc76b43d17/lib/perfSONAR_PS/NPToolkit/DataService/Host.pm#L288

And add the value (commented out) to the default config file.

Also, the GUI should say
```Globally Registered  Disabled```
when the check is disabled (rather than `Yes` or `No`)

**Comment by apertome** [comment]
This was merged a while back; looks good
