### ISSUE TITLE
Option to override hostname

### ISSUE THREAD

**Issue by falz** [perfsonar/toolkit#283]
We (and others?) typically have servers with actual hostname following an internal scheme, and then alias/cname more reasonable hostnames to that host, such as 'perfsonar-foo.fqdn.net".

Suggestion to have a way to override the hostname displayed in the web-ng GUI. 

It currently appears to be set by some DNS lookups in web-ng/root/js/components/HostInfoComponent.js in the HostInfoComponent._setDetails{} function.

If DNS fails it falls back to the toolkit_name that's defined in web-ng/etc/web_admin.conf.

I would suggest flip flopping these to obey toolkit_name if it is set, which would perhaps not be by default. Other suggested method would be some sort of binary toggle to force obeying that flag such as "force_toolkit_name = 1".

**Comment by apertome** [comment]
I like the `force_toolkit_name` flag suggestion, this way we can give people the option of forcing it, without changing the behavior of existing installations.

**Comment by apertome** [comment]
To implement this, we need to add a `force_toolkit_name` flag to `/usr/lib/perfsonar/web-ng/etc/web_admin.conf`, and make the CGIs honor it.

There is already a `toolkit_name` option that allows you to set a default toolkit name, like this:

```toolkit_name perfsonar.example.edu```

However, this only happens if the hostname can't be determined automatically.

We want to add `force_toolkit_name` as an optional parameter. If set to 1, the `toolkit_name` value should be used as the hostname, regardless of is autodetected.

The current behavior should be retained by default.

**Comment by apertome** [comment]
merged
