### ISSUE TITLE
New traceroute visualisation tool

### ISSUE THREAD

**Issue by tonin** [perfsonar/toolkit#323]
UNINETT, in the DragonLab project, is using a nice graphical traceroute visualisation tool. We should look at how we could include it in the toolkit package (and probably then into MaDDash).

The code of this traceroute visualisation will be in the https://github.com/perfsonar/pstracetree repository.

**Comment by arlake228** [comment]
I was able to build and install the perfsonar-pstracetree RPM and get it working, but I see a number of issues with the design:

 * As far as I can tell there is no way to give it an archive URL like https://HOSTNAME/esmond/perfsonar/archive, a source, and a destination then have it find the traceroute. Instead you have to give it a full URL to a traceroute data endpoint like `https://HOSTNAME/esmond/perfsonar/archive/METADATA_ID/packet-trace/base` which is inconvenient and incompatible with the way our other graphs do things. It will make integration with MaDDash much harder as there now needs to be extra information (i.e. the metadata ID) passed when the check on the path is run so maddash can so the traceroute display can work. This just seems inconvenient and it should be a pretty easy lookup for the graph. I see code that looks like it should be doing that in javascript...but it looks like it is doing it incorrectly and filtering on things like "tool-name" instead of "event-type" which will make it unnecessarily  unable to display things that ran "tracepath" or similar.


* Assuming I ignore above and give it a full packet-trace URI, I get a display but have trouble in a few places telling what I am looking at. The graph under the "Topology" tab is straightforward enough...though I had a could rogue circles that I was unclear about (see image below). I am also not sure if it would be better to display 3* differently (maybe indicate a timeout occurred or mark it as unknown and have tooltip explain why it is unknown). 

![image.png](https://images.zenhubusercontent.com/5889306151aa2c305772d655/e8f9c30b-3829-4b4c-9b32-5c8bd5fc95ec)

* Also, in the topology graph, the whitespace is really weird. There seems to be a thick white border where I can't display anything and the graph disappears under. Overall it leads to a lot of wasted space.

* Also, in the topology graph, we should make sure we have units on all the values in the tooltip you get when you click the node.

 * Under "Hop Graph" I am not sure what the size of the circles means,  we should label that/make clearer.

* Under "Hops Stats" the row gets highlighted in pink when you click on a node in "Topology". The his relationship is not clear at all and I only figured it out by accident. I'd either not do the highlight or have some better way to indicate this relationship between tabs. It's really unclear due to the tab structure since the topology gets hidden.
 
Overall this still seems very rough to me. We should discuss this. Given the likely focus on UI items in the post-4.2 timeframe, we may want to hold-off on this until that timeframe so we can get it right.

**Comment by tonin** [comment]
Unfortunately, the tool is not ready for prime-time and inclusion in the toolkit or MaDDash is not possible as-is.  Looking further for solutions in https://github.com/perfsonar/project/issues/1152
