### ISSUE TITLE
service_watcher for central management bundle

### ISSUE THREAD

**Issue by tonin** [perfsonar/toolkit#331]
It would be nice to provide a `service_watcher` script for the central management bundle.  It would need to check on `httpd` and `cassandra` running, but not on owamp and other pscheduler services and removing any dependency to these services.

**Comment by vvidic** [comment]
On Mon, Sep 17, 2018 at 05:48:11AM -0700, Antoine Delvaux wrote:
> It would be nice to provide a `service_watcher` script for the central
> management bundle.  It would need to check on `httpd` and `cassandra`
> running, but not on owamp and other pscheduler services and removing
> any dependency to these services.

On the Debian side perfsonar-toolkit-servicewatcher does not depend on
pscheduler or owamp:

  Depends: libperfsonar-toolkit-perl, perfsonar-common

In fact it seems to work just fine in combination with perfsonar-centralmanagement:

# /usr/lib/perfsonar/scripts/service_watcher --verbose
2018/09/18 15:10:51 (5006) DEBUG> service_watcher:124 main:: - Apache HTTP Server is up
2018/09/18 15:10:52 (5006) DEBUG> service_watcher:124 main:: - Cassandra Database is up
2018/09/18 15:10:52 (5006) DEBUG> service_watcher:119 main:: - Skipping OWAMP
2018/09/18 15:10:52 (5006) DEBUG> service_watcher:119 main:: - Skipping PSConfig PScheduler Agent
2018/09/18 15:10:52 (5006) DEBUG> service_watcher:124 main:: - LS Registration Daemon is up
2018/09/18 15:10:52 (5006) DEBUG> service_watcher:119 main:: - Skipping pScheduler
2018/09/18 15:10:52 (5006) DEBUG> service_watcher:119 main:: - Skipping LS Cache Daemon
2018/09/18 15:10:52 (5006) DEBUG> service_watcher:119 main:: - Skipping perfSONAR Configuration Daemon
2018/09/18 15:10:52 (5006) DEBUG> service_watcher:145 main:: - Apache HTTP Server is up
2018/09/18 15:10:52 (5006) DEBUG> service_watcher:145 main:: - Cassandra Database is up
2018/09/18 15:10:52 (5006) DEBUG> service_watcher:145 main:: - LS Registration Daemon is up

# /usr/lib/perfsonar/scripts/service_watcher --verbose --regular_restart
2018/09/18 15:12:23 (5067) DEBUG> service_watcher:98 main:: - Skipping Apache HTTP Server. doesn't need regular restarts
2018/09/18 15:12:23 (5067) DEBUG> service_watcher:98 main:: - Skipping Cassandra Database. doesn't need regular restarts
2018/09/18 15:12:23 (5067) DEBUG> service_watcher:93 main:: - Skipping OWAMP
2018/09/18 15:12:23 (5067) DEBUG> service_watcher:93 main:: - Skipping PSConfig PScheduler Agent
2018/09/18 15:12:23 (5067) DEBUG> service_watcher:98 main:: - Skipping LS Registration Daemon. doesn't need regular restarts
2018/09/18 15:12:23 (5067) DEBUG> service_watcher:93 main:: - Skipping pScheduler
2018/09/18 15:12:23 (5067) DEBUG> service_watcher:93 main:: - Skipping LS Cache Daemon
2018/09/18 15:12:23 (5067) DEBUG> service_watcher:93 main:: - Skipping perfSONAR Configuration Daemon
2018/09/18 15:12:24 (5067) DEBUG> service_watcher:124 main:: - Apache HTTP Server is up
2018/09/18 15:12:24 (5067) DEBUG> service_watcher:124 main:: - Cassandra Database is up
2018/09/18 15:12:24 (5067) DEBUG> service_watcher:119 main:: - Skipping OWAMP
2018/09/18 15:12:24 (5067) DEBUG> service_watcher:119 main:: - Skipping PSConfig PScheduler Agent
2018/09/18 15:12:24 (5067) DEBUG> service_watcher:124 main:: - LS Registration Daemon is up
2018/09/18 15:12:24 (5067) DEBUG> service_watcher:119 main:: - Skipping pScheduler
2018/09/18 15:12:24 (5067) DEBUG> service_watcher:119 main:: - Skipping LS Cache Daemon
2018/09/18 15:12:24 (5067) DEBUG> service_watcher:119 main:: - Skipping perfSONAR Configuration Daemon
2018/09/18 15:12:24 (5067) DEBUG> service_watcher:145 main:: - Apache HTTP Server is up
2018/09/18 15:12:24 (5067) DEBUG> service_watcher:145 main:: - Cassandra Database is up
2018/09/18 15:12:24 (5067) DEBUG> service_watcher:145 main:: - LS Registration Daemon is up

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by tonin** [comment]
Great! Can we then make the RPM work in a similar way?

**Comment by vvidic** [comment]
On Wed, Sep 19, 2018 at 12:42:36PM -0700, Antoine Delvaux wrote:
> Great! Can we then make the RPM work in a similar way?

Ok, I will check CentOS side too...

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by vvidic** [comment]
On Wed, Sep 19, 2018 at 12:42:36PM -0700, Antoine Delvaux wrote:
> Great! Can we then make the RPM work in a similar way?

It seems to work the same way on CentOS too:

# /usr/lib/perfsonar/scripts/service_watcher --verbose 
2018/09/20 01:52:45 (3589) DEBUG> service_watcher:124 main:: - Apache HTTP Server is up
2018/09/20 01:52:45 (3589) DEBUG> service_watcher:124 main:: - Cassandra Database is up
2018/09/20 01:52:45 (3589) DEBUG> service_watcher:119 main:: - Skipping OWAMP
2018/09/20 01:52:45 (3589) DEBUG> service_watcher:119 main:: - Skipping PSConfig PScheduler Agent
2018/09/20 01:52:45 (3589) DEBUG> service_watcher:124 main:: - LS Registration Daemon is up
2018/09/20 01:52:45 (3589) DEBUG> service_watcher:119 main:: - Skipping pScheduler
2018/09/20 01:52:45 (3589) DEBUG> service_watcher:119 main:: - Skipping LS Cache Daemon
2018/09/20 01:52:45 (3589) DEBUG> service_watcher:119 main:: - Skipping perfSONAR Configuration Daemon
2018/09/20 01:52:45 (3589) DEBUG> service_watcher:145 main:: - Apache HTTP Server is up
2018/09/20 01:52:45 (3589) DEBUG> service_watcher:145 main:: - Cassandra Database is up
2018/09/20 01:52:45 (3589) DEBUG> service_watcher:145 main:: - LS Registration Daemon is up

Not sure what the problem was then because there is no depends on owamp
or pscheduler here either. Could it be that ansible pulled those in somehow?

# yum deplist perfsonar-toolkit-servicewatcher
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.lihnidos.org
 * epel: ftp.arnes.si
 * extras: mirror.lihnidos.org
 * perfSONAR: mirror.in2p3.fr
 * updates: mirror.lihnidos.org
package: perfsonar-toolkit-servicewatcher.noarch 4.1.2-1.el7
  dependency: /bin/sh
   provider: bash.x86_64 4.2.46-30.el7
  dependency: /usr/bin/perl
   provider: perl.x86_64 4:5.16.3-292.el7
  dependency: coreutils
   provider: coreutils.x86_64 8.22-21.el7
  dependency: libperfsonar-toolkit-perl
   provider: libperfsonar-toolkit-perl.noarch 4.1.2-1.el7
  dependency: ntp
   provider: ntp.x86_64 4.2.6p5-28.el7.centos
  dependency: perfsonar-common
   provider: perfsonar-common.noarch 4.1.2-1.el7
  dependency: perfsonar-toolkit-library
   provider: perfsonar-toolkit-library.noarch 4.1.2-1.el7
  dependency: perl(Config::General)
   provider: perl-Config-General.noarch 2.61-1.el7
  dependency: perl(Data::Dumper)
   provider: perl-Data-Dumper.x86_64 2.145-3.el7
  dependency: perl(FindBin)
   provider: perl.x86_64 4:5.16.3-292.el7
  dependency: perl(Getopt::Long)
   provider: perl-Getopt-Long.noarch 2.40-3.el7
  dependency: perl(Log::Log4perl)
   provider: perl-Log-Log4perl.noarch 1.42-2.el7
  dependency: perl(Params::Validate)
   provider: perl-Params-Validate.x86_64 1.08-4.el7
  dependency: perl(lib)
   provider: perl.x86_64 4:5.16.3-292.el7
  dependency: perl(perfSONAR_PS::NPToolkit::Services::ServicesMap)
   provider: libperfsonar-toolkit-perl.noarch 4.1.2-1.el7
  dependency: perl(strict)
   provider: perl.x86_64 4:5.16.3-292.el7
  dependency: perl(warnings)
   provider: perl.x86_64 4:5.16.3-292.el7
  dependency: rpm
   provider: rpm.x86_64 4.11.3-32.el7

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by tonin** [comment]
Ok, thanks for checking.  I guess I must have been trying to install multiple things at the same time.
