### ISSUE TITLE
Use system gids for esmond and perfsonar users

### ISSUE THREAD

**Issue by candlerb** [perfsonar/toolkit#340]
Whilst the `esmond` and `perfsonar` users are currently created with system uids, they are getting non-system gids:

/etc/passwd:

```
esmond:x:993:1001:Esmond User:/tmp:/sbin/nologin
perfsonar:x:991:1002:perfSONAR User:/tmp:/sbin/nologin
```

/etc/group:

```
esmond:x:1001:
perfsonar:x:1002:
```

Tested with perfsonar toolkit 4.1.2 ISO

Related to https://github.com/perfsonar/pscheduler/issues/694 for `pscheduler` and `pssudo`:

> All creation of users and groups should be done with the -r switch to make them system instead of normal.

**Comment by arlake228** [comment]
For the hackathon: It looks like `useradd` is ok in all the .spec files (wouldn't hurt to double-check) but `groupadd` is missing `-r` (or alternatively `--system`) almost everywhere.

**Comment by arlake228** [comment]
Projects to review:

* [ ] psconfig 
* [ ] toolkit 
* [ ] graphs
* [ ] bundles
* [ ] owamp
* [ ] perl-shared
* [ ] psTracerouteViewer
* [ ] ls-cache-daemon
* [ ] nagios 
* [ ] ls-registration-daemon
* [ ] i2util
* [ ] esmond
* [ ] maddash
* [ ] perfsonar-repo

**Comment by mfeit-internet2** [comment]
What was inspected, fixed and branch where the fix was applied:

### USERADD:

bundles - Already OK
esmond - Already OK
graphs - Already OK
i2util - No useradd
ls-cache-daemon - Already OK
ls-registration-daemon - Already OK
maddash - Already OK
nagios - Already OK
owamp - Already OK
perfsonar-repo - No useradd
perl-shared - Already OK
psconfig - Already OK
psTracerouteViewer - Already OK
toolkit - Already OK

### GROUPADD:

bundles - Fixed / 4.2.0
esmond - Fixed / master
graphs - Fixed / master
i2util - No groupadd
ls-cache-daemon - Fixed / master
ls-registration-daemon - Fixed / master
maddash - Fixed / 4.2.0
nagios - Fixed / 4.2.0
owamp - No groupadd
perfsonar-repo - No groupadd
perl-shared - Fixed / 4.2.0
psconfig - Fixed / 4.2.0
psTracerouteViewer - Fixed / master
toolkit - Fixed / 4.2.0

**Comment by tonin** [comment]
Debian is using adduser and addgroup only in:
- esmond - already Ok on 4.2.0
- maddash - already Ok on 4.2.0
- owamp - already Ok on 4.2.0
- perlshared - already Ok on 4.2.0

For the Debian packages, all the perfsonar user creation is handled by a single package: **perfsonar-common** which lives inside the perl-shared repo.  All the packages that are relying on the perfsonar user depends on this package.

**Comment by arlake228** [comment]
Looks good, closing.
