### ISSUE TITLE
non-root user accounts not restored by migration script

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/toolkit#354]
I'm not sure this is a feature or a bug.
The script used for pS migration doesn't restore non-root accounts on a fresh install although it backs them up. I migrated from CentOS6 4.0.2 to 4.1.3

Here is the issue:
1) I created backup data with ps-migrate-backup.sh. Went ok. The content of /passwd in the tar file is:
pswebadmin:x:500:504::/home/pswebadmin:/bin/false
psudouser:x:501:505::/home/psudouser:/bin/bash
geantadmin:x:502:506:GÉANT admin user:/home/geantadmin:/bin/bash
pscheduler:x:503:507:pScheduler:/home/pscheduler:/bin/bash

2) I installed fresh Toolkit. I didn't configure psudouser not webadmin user yet. And the content of /etc/passwd just after fresh installation is:
[root@psmall-poz1 ~]# awk -F: '($3>=500) && ($3!=65534)' /etc/passwd
nagios:x:999:999::/var/spool/nagios:/sbin/nologin
pscheduler:x:1000:1000:pScheduler:/home/pscheduler:/bin/bash
cassandra:x:998:998::/usr/share/cassandra:/bin/bash
polkitd:x:997:996:User for polkitd:/:/sbin/nologin
owamp:x:996:995::/tmp:/bin/nologin
libstoragemgmt:x:995:993:daemon account for libstoragemgmt:/var/run/lsm:/sbin/nologin
memcached:x:994:992:Memcached daemon:/run/memcached:/sbin/nologin
perfsonar:x:993:1001:perfSONAR User:/tmp:/sbin/nologin
esmond:x:992:1002:Esmond User:/tmp:/sbin/nologin
twamp:x:991:990::/tmp:/bin/nologin
chrony:x:990:988::/var/lib/chrony:/sbin/nologin
[root@psmall-poz1 ~]#

3) I'm restoring configuration:
[root@psmall-poz1 ~]# /usr/lib/perfsonar/scripts/ps-migrate-restore.sh ~/ps-backup.tgz
WARN: Looks like non-root user accounts were created prior to running this script. Skipping user account restoration to avoid conflicts
Restoring perfsonar configuration...[SUCCESS]
Restoring owamp-server configuration...[SUCCESS]
Restoring NTP configuration...[SUCCESS]

WARNING

So the issue is why the accounts were not restored although it was a fresh installation and no changes made...

**Comment by arlake228** [comment]
It looks like it only restores if there are no users with a GID above 500. I think the minimum regular user id got bumped to 1000 in CentOS 7, so that is not the right check since it will be impossible to pass. We probably also don't want to preserve those smaller GIDs on the new system, so need to think about how we want to handle that. This right answer might be that we just don't migrate users (which is essentially what happens now). Also related to perfsonar/pscheduler#694 since it is getting created as a regular user which will short circuit the check even if the minimum is 100. 

The devs should briefly discuss this on one of our calls to figure out the right strategy. If the answer is we don't migrate non-system users then e need to document that fact and update the script to slip that portion of the code.

**Comment by arlake228** [comment]
We decided on the dev call to no longer migrate the non-system users. The tasks are now to:

[ ] Update the script so it does not try to migrate users
[ ] Document the fact that it does not migrate users
