### ISSUE TITLE
CentOS8 release

### ISSUE THREAD

**Issue by juztas** [perfsonar/toolkit#413]
Title speaks by itself ;)

**Comment by mfeit-internet2** [comment]
Support for CentOS 8 in its current form is unlikely since support is being ended eight years early.  Support for CentOS Stream is also unlikely because it's not derived from stable code and our users don't seem very enthusiastic about adopting it.  There's some early discussion about that here:  https://lists.internet2.edu/sympa/arc/perfsonar-user/2020-12/msg00020.html

The only real change in the landscape has been the first stable release of Alma Linux last month.  We still need input from the community about where they're going so we can make decisions about what to support.  Four months into this, I think most organizations are still trying to decide that for themselves.
