### ISSUE TITLE
opensearch permissions in toolkit 5.1 

### ISSUE THREAD

**Issue by rhclopes** [perfsonar/toolkit#467]
There  are quite a few warnings in the the open search logs (see attached file) related to opensearch configuration files that are worldwide readable when they should only be accessible to root and opensearch.

It should be trivial to fix in a minor release 

[opensearch-permissions.txt](https://github.com/perfsonar/toolkit/files/14775233/opensearch-permissions.txt)

**Comment by rhclopes** [comment]
There was a minor release yesterday that killed opensearech. I restarted today and I see a complaint in systemd.

See attached opensearch systems complain.

[opoensearch-systemd-20240402.txt](https://github.com/perfsonar/toolkit/files/14841306/opoensearch-systemd-20240402.txt)

After restart, systems says that opensearch is active, but archive troubleshoot fails. It was not failing last week.

See attached.

[archiver-troubleshoot.txt](https://github.com/perfsonar/toolkit/files/14841319/archiver-troubleshoot.txt)

**Comment by arlake228** [comment]
We were testing an opensearch update yesterday and the opensearch rpm blasted some files that broke the auth with logstash. I think the most recent updates should fix your node.

The file permissions which are what this issue is about should be fixed now as well. The other warnings you shared seem internal to opensearch and should be harmless.
