### ISSUE TITLE
Minor 5.1 Toolkit GUI issues

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/toolkit#472]
Here is what I noticed:

- [x] In Home page when Full Test Listing panel is collapsed page footer (i.e. "Privacy Policy | Global Node Directory | Host JSON" links) is not visible. When clicked to show this panle then footer is visible.
- [x] In Home page when clicked in the footer "Host JSON" link then "Page not found" is shown
- [x] In Host info section in the panel showing network traffic I can see more then one interface (in my test host it is a wireless if) while in the "Interfaces" table on the right only one interface is listed. It's misleading and I think it should list the same things
- [x] When switched to Configuration and old Toolkit part, under "Administrative Information" tab in my installation the Country drop-down list is empty... It just shows "--Select Country--"

All tested under Ubuntu 20

![toolkit_if](https://github.com/perfsonar/toolkit/assets/12281679/994e59b3-8931-4da1-8dea-7069a6ad250b)

**Comment by szymontrocha** [comment]
At least the last issue seen also under Ubuntu 22

**Comment by arlake228** [comment]
Fixed the first three, starting on second:

1. I changed this to just be a heading instead of collapsable. we don't need to collapse it and there is no way to prevent it from sucking up everything underneath.
2. I kinda cheated here and removed the link. the problem is that it adds /grafana to the link since grafana is behind a proxy. We don't really want to be pushing that interface anymore anyways, so probably dont need link there.
3. This got fixed as part of the issue where i moved from interface to IP. TL;DR the main page needed some more filters. They are consistent now as i ran into some similar issues.
