### ISSUE TITLE
NetInstall installer doesn't go into graphical mode

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/toolkit#65]
Trying to install NetInstall rc2 and selecting the first initial menu item which should lead to graphical installer it goes to text mode instead. Second menu item also leads to text mode.

**Comment by arlake228** [comment]
It may be confusing because the first few prompts are in text mode. It asks you about your language and keyboard (maybe some other stuff), then has a progress bar that says something like "Retrieving install.img". After install.img downloads, it should jump to graphical mode. Did you get past these first few prompts and it was still text mode?

**Comment by szymontrocha** [comment]
ok, I see now. Will go further and add some note in the guide

**Comment by szymontrocha** [comment]
Closing this one then and will open for docs
