### ISSUE TITLE
Bundle installation and SElinux

### ISSUE THREAD

**Issue by tonin** [perfsonar/toolkit#68]
When one installs the perfSONAR-Complete bundle it is not possible to login to the toolkit webinterface with any newly created user.  The selinux context of `/etc/shadow` prevents mod_auth_shadow to read the users and their passwords.  One has to disable selinux to make it work.

Could we provide an updated selinux policy to enable that?

**Comment by tonin** [comment]
Meanwhile, this has been documented at http://docs.perfsonar.net/install_centos.html#configuring-through-the-web-interface

**Comment by tonin** [comment]
One can get apache to correctly read the `/etc/shadow` file by enabling the selinux boolean `allow_httpd_mod_auth_pam`:

    setsebool allow_httpd_mod_auth_pam on

Authentication to the toolkit web interface is then possible.  However there are a lot of other SElinux violation that prevent the perfSONAR toolkit from working.  We would need to look deeper into that.

**Comment by tonin** [comment]
This needs to be reviewed in light of the changes to the authentication module, see https://github.com/perfsonar/toolkit/commit/65194bb

We also need to look at possible other issues with SELinux and the toolkit.  A standard toolkit install (from ISO image) does set SElinux to permissive.

**Comment by arlake228** [comment]
I think we agreed last week that this can get moved out to a future release. I agree that in light of the recent change to auth, the specific issue mentioned related to auth_shadow is less of a concern.

**Comment by somedatapacket** [comment]
@apertome in light of your help last week with the U-M host, I'm curious about this issue. In this thread, @tonin notes that a standard toolkit install from ISO has SElinux set to permissive. Is it possible to set SElinux to permissive on CentOS 7 during the rpm install process as well?

**Comment by apertome** [comment]
@somedatapacket it seems like that might be a good idea. @arlake228 is really the best person to answer this question, though.

**Comment by arlake228** [comment]
Seems like the toolkit package should do that. I would have thought that it
already does, but I guess I’ll have to look to see if that happens in the
kickstart or the RPM layer.


On February 13, 2017 at 9:50:35 AM, Michael Johnson (
notifications@github.com) wrote:

@somedatapacket <https://github.com/somedatapacket> it seems like that
might be a good idea. @arlake228 <https://github.com/arlake228> is really
the best person to answer this question, though.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/perfsonar/toolkit/issues/68#issuecomment-279412886>,
or mute
the thread

**Comment by bltierney** [comment]
has this been fixed?

**Comment by arlake228** [comment]
Looks like the kickstarts disable selinux, so the RPM does not touch it. Pushing this to 4.1 as i am not sure the RPMs should be messing with a pre-existing systems selinux config or not.

**Comment by vvidic** [comment]
Do we merge this into 4.2 branch now?

**Comment by vvidic** [comment]
Merged for 4.2.0 release.
