### ISSUE TITLE
Cassandra complaint

### ISSUE THREAD

**Issue by igarny** [perfsonar/toolkit#81]
Hi Andy,

I have been following as much as possible the recommended setup with pS toolkits. I see a strange warning and suggestion for an optimization.

> INFO [main] 2015-12-14 11:54:03,283 CassandraDaemon.java (line 217) JVM vendor/version: OpenJDK 64-Bit Server VM/1.7.0_85
> WARN [main] 2015-12-14 11:54:03,283 CassandraDaemon.java (line 222) OpenJDK is not recommended. Please upgrade to the newest Oracle Java release

There isn't much of a problem with this, but with operations it is always the case that we seek performance and minimization on resource requirements.

Are you able to share concerns for not following the recommendation of Cassandra?

Best regards,
Ivan

**Comment by arlake228** [comment]
Hi,

It’s up to you if you want to use Oracle instead. I am not aware of any issues we have ran into because we use OpenJDK instead of the Oracle versions. I don’t believe Oracle sticks version of its RPMs in the CentOS repo so you will have to fetch those yourself. I would guess it’s more trouble than it’s worth.

Thanks,
Andy




On December 15, 2015 at 4:51:21 AM, Ivan Garnizov (notifications@github.com) wrote:

Hi Andy,

I have been following as much as possible the recommended setup with pS toolkits I see a strange warning and suggestion for an optimization

INFO [main] 2015-12-14 11:54:03,283 CassandraDaemonjava (line 217) JVM vendor/version: OpenJDK 64-Bit Server VM/170_85
WARN [main] 2015-12-14 11:54:03,283 CassandraDaemonjava (line 222) OpenJDK is not recommended Please upgrade to the newest Oracle Java release

There isn't much of a problem with this, but with operations it is always the case that we seek performance and minimization on resource requirements

Are you able to share concerns for not following the recommendation of Cassandra?

Best regards,
Ivan
