### ISSUE TITLE
Make iptables Chains More Efficient

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/toolkit#82]
The current arrangement of the [iptables configuration](https://github.com/perfsonar/toolkit/blob/master/etc/perfsonar_firewall_settings.conf)  doesn't lend itself to efficiently processing time- and rate-sensitive traffic.  That traffic should be checked *first* so each frame isn't subjected to lots of additional tests.

The table on the running CentOS version of the toolkit ends up containing several duplicate checks that could be eliminated and a number of adjacent ranges that could be folded into one.  

**Short-Term Fix:**

* Re-order the checks so throughput and latency traffic is tested before everything else.
* Combine checks of adjacent port ranges.
* Figure out why the running CentOS version of the toolkit ends up with duplicate entries even though the file in the source has none.  Looks like there are places in configure_firewall at about lines 188 and 204 where the same test is being added/removed twice; is there a reason for that?

**Long-Term Fix:**

* Create a `.d`-type directory where packages can deposit flat files listing the ranges, protocols and priorities of the ports they use.
* Develop a program which reads those files, combines adjacent/overlapping ranges and generates a chain that does the checks in priority-order.

**Comment by tonin** [comment]
I've not addressed any long-term fix nor the combination of checking adjacent port ranges, but I've solved the rule duplication and have proposed a re-ordering of ports for better performance.

Two comments:
- the ports for BWCTL and OWAMP are read from their own configuration files, making the `configure_firewall` script suitable for sites that don't use the usual ranges,
- the `ESTABLISHED` state checking is not needed because the default iptables setup on CentOS already has such a rule at the very beginning of the ruleset.

Please review my patch for inclusion in 3.5.1 if suitable.

**Comment by tonin** [comment]
We also need to correct the documentation afterwards because the port duplication is there too!  http://docs.perfsonar.net/manage_security.html
